language: rust
cache: cargo
dist: xenial
sudo: true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
    - zlib1g-dev

# Run builds in Linux, MacOS X and Windows
os:
- linux
- osx
- windows

# Run builds for all the supported trains
rust:
- 1.37.0
- stable
- beta
- nightly

stages:
- test
- deploy

# Extra jobs to include
jobs:
  include:
  # Upload documentation
  - name: "Documentation upload"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DOCS
    script: ./travis-helper.sh documentation
    deploy: &pages
      provider: pages
      github-token: $GH_TOKEN
      local-dir: target/doc/
      skip_cleanup: true
      keep-history: true
      on:
        repo: SUPERAndroidAnalyzer/dalvik
        branch: develop

matrix:
  fast_finish: true
  allow_failures:
  - os: windows

# Run the multiple tests.
script:
- ./travis-helper.sh fmt_check
- ./travis-helper.sh clippy_check
- ./travis-helper.sh test

# Upload code coverage report
after_success:
- ./travis-helper.sh upload_code_coverage

notifications:
  email:
    recipients:
    - razican@protonmail.ch
    - brunoop@protonmail.ch
    - sergiodlo@protonmail.com
    - jaimesr@protonmail.ch
    on_success: change
    on_failure: always
