var N = null;var sourcesIndex = {};
sourcesIndex['backtrace'] = {"name":"","dirs":[{"name":"backtrace","dirs":[],"files":["libunwind.rs","mod.rs"]},{"name":"symbolize","dirs":[],"files":["libbacktrace.rs","mod.rs"]}],"files":["capture.rs","dylib.rs","lib.rs","types.rs"]};
sourcesIndex['backtrace_sys'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['bitflags'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['byteorder'] = {"name":"","dirs":[],"files":["io.rs","lib.rs"]};
sourcesIndex['cfg_if'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['dalvik'] = {"name":"","dirs":[{"name":"types","dirs":[],"files":["read.rs"]}],"files":["bytecode.rs","error.rs","header.rs","lib.rs","read.rs","sizes.rs","types.rs"]};
sourcesIndex['failure'] = {"name":"","dirs":[{"name":"backtrace","dirs":[],"files":["internal.rs","mod.rs"]},{"name":"error","dirs":[],"files":["error_impl.rs","mod.rs"]}],"files":["as_fail.rs","box_std.rs","compat.rs","context.rs","error_message.rs","lib.rs","macros.rs","result_ext.rs","sync_failure.rs"]};
sourcesIndex['failure_derive'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['libc'] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"notbsd","dirs":[{"name":"linux","dirs":[{"name":"other","dirs":[{"name":"b64","dirs":[],"files":["mod.rs","not_x32.rs","x86_64.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["dox.rs","lib.rs","macros.rs"]};
sourcesIndex['proc_macro2'] = {"name":"","dirs":[],"files":["fallback.rs","lib.rs","strnom.rs","wrapper.rs"]};
sourcesIndex['quote'] = {"name":"","dirs":[],"files":["ext.rs","lib.rs","to_tokens.rs"]};
sourcesIndex['rustc_demangle'] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex['syn'] = {"name":"","dirs":[{"name":"gen","dirs":[],"files":["gen_helper.rs","visit.rs"]}],"files":["attr.rs","buffer.rs","data.rs","derive.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","keyword.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","span.rs","spanned.rs","thread.rs","token.rs","tt.rs","ty.rs"]};
sourcesIndex['synstructure'] = {"name":"","dirs":[],"files":["lib.rs","macros.rs"]};
sourcesIndex['unicode_xid'] = {"name":"","dirs":[],"files":["lib.rs","tables.rs"]};
